### ISSUE TITLE
32blit-stm32 - Investigate SD-card IO speed

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/32blit-beta#1]
SD card throughput has been less than stellar, and while we're using a 1-bit bus I don't believe we're quite as close to the theoretical maximum speed as it's possible to get. Looking over the SD card code reveals codepaths and potential inefficiencies that could cause slowdown, I've fixed some of these with significant resulting gains in performance. I think it's worth trying to find more opportunity to eke throughput out of the SD card.

**Comment by Gadgetoid** [comment]
I think https://github.com/pimoroni/32blit-beta/commit/8c1c1bb63184bc30d229c6428c2f5ca96e8ab0f7 finally brought SD card performance up to reasonable levels.

However I have personally seen issues running the SPI interface with `SPI_BAUDRATEPRESCALER_4` on some SD cards versus `SPI_BAUDRATEPRESCALER_8` which brings the speed, in theory, back down to rates prior to this fix.

Some method of detecting the SD card, trying `SPI_BAUDRATEPRESCALER_4` and failing back to `SPI_BAUDRATEPRESCALER_8` would be great for best performance, but for now we might need to drop to `SPI_BAUDRATEPRESCALER_4` in order to maximise compatibility and minimise "why isn't my SD card working?" questions.

**Comment by Daft-Freak** [comment]
I don't know what the clock with _4 is, but if it's > 25Mhz, you need to switch the card into "high speed" mode first. Also, you're meant to init with a clock of 400kHz.

(I dug up my notes from when I was attempting to get SD cards working.)
