### ISSUE TITLE
Consider introducing a Buttons type as a scoped enumeration

### ISSUE THREAD

**Issue by Pharap** [pimoroni/32blit-beta#118]
In follow up to #105, using C++11's `enum class` it would be possible to define a type-safe enumeration type representing a set of button states.

This would function similarly to the current situation in that you could define bitwise operators to operate on the type, but it would prevent certain accidents that might occur by using a non-typesafe solution such as `std::uint16_t` or a plain `enum`.

For example, one common mistake made by some people when using bitsets is to try to combine bits using `+` instead of `|`, which can lead to errors if the same bit is added twice, or if two bits overlap.
E.g. `buttons = blit::Button::A + blit::Button::B + blit::Button::A`.

With scoped enumerations, which are not implicitly convertible to `int`, you could either implement `operator +` in terms of `|`, or disallow `operator +` altogether, thus preventing this scenario.

As I'm sure you can imagine, there are a number of similar situations in which `enum`'s ability to be implicitly converted to `int` can cause subtle bugs or errors that will not be detected by the compiler as they may well appear to it as being intentional.

It is entirely possible to convert a scoped enumeration to an integer by manual conversion with a `static_cast` or C-style cast if need be, but in the majority of cases that should be unnecessary as the bitwise operations should suffice.

Ultimately the biggest benefit is that it creates a designated (type-safe) type that represents a group of buttons, which makes code that interacts with and manipulates buttons much more self-descriptive.

---

Of course, nothing in life is free, there are a few potential downsides,
mostly in relation to backwards compatibility with exsting code:

One potential downside is that this change would prevent the practice of writing code like `if(blit::buttons & blit::buttons::A)` and would force the practice of the more verbose `if((blit::buttons & buttons::A) != buttons::None)` because it is not possible to define a conversion operator for a scoped enumeration.

One other potential downside is that you wouldn't be able to write `blit::A` instead of `blit::Button::A`, which might break some existing code, but arguably this is actually a benefit because `blit::A` is not very descriptive.

---

I'd like to note that this change would not preclude the #63 proposal and could easily work in conjunction with it.

**Comment by Gadgetoid** [comment]
This was a welcome suggestion and I’m sorry it didn’t get the attention it deserved! Was hoping someone else with a little more C++ experience would chime in, since I’m certainly not an expert.

Right now input has changed somewhat, and we’re quite far toward a mature API so I don’t think this suggestion would be worth implementing. But thank you for taking the time to make it and detail the pros/cons so comprehensively!
