### ISSUE TITLE
32blit - Namespace pollution

### ISSUE THREAD

**Issue by ali1234** [pimoroni/32blit-beta#18]
The following engine headers include `using namespace blit;`.

- [ ] types/map.hpp
- [ ] graphics/surface.hpp
- [ ] graphics/tilemap.hpp

This causes every file that includes them to also use the namespace, leading to random name collisions in user code. This filters through to any file that includes `32blit.hpp`.

Note that fixing this will probably break all the examples that don't already contain `using namespace blit;`.

**Comment by Gadgetoid** [comment]
Let it be said that I broadly hate the use of `using namespace blit;` and would probably prefer everything to use the longform, namespace-qualified names. It leaves much less opportunity for name conflicts, or shadowing? Is that even a thing in C++. Although I can't say something if like `colour = blit::colour(0,0,0);` is more or less desirable.

I guess I can't shake that it reminds me of one of my most-hated Python code-smells: `import numpy as np`.

**Comment by ali1234** [comment]
The issue here is using it inside headers - it's fine if you do it inside the .cpp because it will never affect user code.

And yes name shadowing most certainly is a thing. I have a variable called buttons and the IDE complains that it shadows blit::buttons everywhere.
