### ISSUE TITLE
blit::debug() crashes on device

### ISSUE THREAD

**Issue by ali1234** [pimoroni/32blit-beta#20]
`blit::debug()` is defined in the SDL HAL, but currently not the STM32 HAL. Calling it will cause the program to crash spectacularly.

**Comment by Gadgetoid** [comment]
This should be fixed as of c4a56e868acb43fd9783bfa769a8b069e2f6cfb7 where `blit::debug()` is defined as a basic function to print text to the top left of the screen.

This will be fleshed out in future and we're discussing adding features like:

* On screen debug output
* Debug output over USB serial
* Debug log to SD card
