### ISSUE TITLE
When using dma2d for flip, you don't need invalidate the ltdc buffer anymore

### ISSUE THREAD

**Issue by zenodante** [pimoroni/32blit-beta#249]
Hi, 
In branch 32blit-ltdc-buff branch:
Display.cpp:
192 SCB_CleanInvalidateDCache_by_Addr((uint32_t *)(&__ltdc_start), ltdc_buffer_size);   
As the DMA2d don't go through cache, so after the flip operation, the invalidate is not necessary.

Best regards,

Ming

**Comment by lowfatcode** [comment]
Ahh yes, that's there from the previous setup where we wrote the data directly into the LTDC buffer area. It'll still be needed (at the moment) for the lores flip!

**Comment by Gadgetoid** [comment]
Think now lores is dma2d also, this is obsolete?
