### ISSUE TITLE
blit::circle is 1 pixel too narrow

### ISSUE THREAD

**Issue by ali1234** [pimoroni/32blit-beta#31]
This one is definitely wrong. Code:

```
    blit::fb.pen(blit::rgba(0, 0, 0));
    blit::fb.circle(blit::point(4, 4), 3);
```

Result:

![circle](https://user-images.githubusercontent.com/651970/71637368-68216b00-2c39-11ea-8230-08c120a7c880.png)

**Comment by Gadgetoid** [comment]
That's... uh... definitely *not* a circle!
