### ISSUE TITLE
Tilemap test issues

### ISSUE THREAD

**Issue by Daft-Freak** [pimoroni/32blit-beta#340]
- ~prespective dies with `Uncaught RuntimeError: invalid conversion to integer` on Emscripten~
- betamax appears to be dividing by 0 (`Uncaught RuntimeError: integer divide by zero` on Emcripten, `Floating point exception` on Linux)

**Comment by Gadgetoid** [comment]
Fixed point 2 in #359

**Comment by Daft-Freak** [comment]
Now the only thing left is that the `perspective` effect does a (float) divide by zero for line 0, resulting in a matrix of nans.

Also, most of the effects have a comment of `apply dream wave effect`...

**Comment by Daft-Freak** [comment]
Looks like everything is working now!
