### ISSUE TITLE
Input.cpp action buttons "SDLK_y,       blit::button::Y" should be SDLK_v

### ISSUE THREAD

**Issue by zenodante** [pimoroni/32blit-beta#39]
// action buttons
	{SDLK_z,       blit::button::A},
	{SDLK_x,       blit::button::B},
	{SDLK_c,       blit::button::X},
	{SDLK_y,       blit::button::Y},

zxcv?

**Comment by Gadgetoid** [comment]
🤔 

https://github.com/pimoroni/32blit-beta/blob/1e829fc70fff8b83775b8f57894819b5c86cde40/32blit-sdl/Input.cpp#L21-L24

To be honest I like using WASD and maybe UIOP (or a controller), but yes something is clearly awry here.
