### ISSUE TITLE
As the 32blit hardware is using rev. V chip, We could tune off this work around to increase the axi speed

### ISSUE THREAD

**Issue by zenodante** [pimoroni/32blit-beta#438]
https://github.com/pimoroni/32blit-beta/blob/6080222d2aeff927c1026b0e5630818aedfb1767/32blit-stm32/Src/system_stm32h7xx.c#L233

According to the stm32h750 errata sheet, the issue 2.2.9 only accoured in rev. Y chip. If all 32blit hardware are using 480mhz rev. V chip. It is not necessary to set this work around any more. Then it will increase the read issuing capability and improve the CPU speed on memory bus.

In errata sheet page 13:
"2.2.9 Reading from AXI SRAM may lead to data read corruption
Description
Read data may be corrupted when the following conditions are met:
• Several read transactions are performed to the AXI SRAM,
• and a master delays its data acceptance while a new transfer is requested.
Workaround
Set the READ_ISS_OVERRIDE bit in the AXI_TARG7_FN_MOD register. This will reduce
the read issuing capability to 1 at AXI interconnect level and avoid data corruption."

**Comment by Gadgetoid** [comment]
Oo, any reason why you closed this? I tried to follow the IF/ELSE flow around that particular snippet of code, and ... well it's painful! Is it something we're already inadvertently excluding via a compiler definition?
