### ISSUE TITLE
Graphical corruption when installing a game with no metadata

### ISSUE THREAD

**Issue by ali1234** [pimoroni/32blit-beta#470]
![screenshot0](https://user-images.githubusercontent.com/651970/102626465-bb3c4880-413e-11eb-90ab-3729be4dd1b0.jpg)

There should be some kind of fallback to prevent this from happening. Either in the launcher, or by providing default metadata during build if metadata.yaml is not present.

**Comment by ahnlak** [comment]
I would say in the launcher (at least); feels risky to rely solely on the build

**Comment by ali1234** [comment]
Agree, but it may not be possible depending on how the metadata is formatted inside the binary.

**Comment by Daft-Freak** [comment]
There's a sort-of fallback now in that the metadata is blank and the title is "game@[block]". Could certainly be improved a bit though.

**Comment by ali1234** [comment]
I just realised that my screenshot doesn't show corruption. That is just what "@" looks like in the tiny font.
