### ISSUE TITLE
Improve button handling in the API

### ISSUE THREAD

**Issue by lenardg** [pimoroni/32blit-beta#63]
Currently the API provides us with button statuses only (is it pressed or is it released). The demo game scrolly-tile does some bitfield magic to keep track of what is actually done with the buttons - and not just if it is held or not. 

Relevant code:
``` C++
	uint16_t changed = blit::buttons ^ last_buttons;
	uint16_t pressed = changed & blit::buttons;
	uint16_t released = changed & ~blit::buttons;
```

It would be great if this same functionality would be part of the engine. 

Instead of just `blit::buttons` it could be a struct of some kind, where you would have three members:

* `status` - to check the status of a single button, like what blit::buttons is now.
* `pressed` - that would tell which button was pressed since last time
* `released` - that would tell which button was released since last time

ALthough it might be a little bit long to write, it would increase clarity.

For example: `if ( blit::buttons::pressed & blit::button::A )`

**Comment by ali1234** [comment]
You can avoid the complement operation:

    uint16_t released = changed & last_buttons;

**Comment by Daft-Freak** [comment]
I think I did (quite close to) this in #310?
