### ISSUE TITLE
SD Card Access

### ISSUE THREAD

**Issue by trollied** [pimoroni/32blit-beta#64]
There are currently no user-side blit:: API functions for accessing a SD card.

**Comment by Gadgetoid** [comment]
We're slowly working these out- particularly in respect to Jon's voxel demo, which currently streams assets from the SD card. Some good suggestions over on #62

**Comment by Gadgetoid** [comment]
I think this has been thoroughly solved by @Daft-Freak's comprehensive File API and perhaps best exemplified in his projects:

* https://github.com/Daft-Freak/32blit-music-player
* https://github.com/Daft-Freak/32blit-mjpeg-player
* https://github.com/Daft-Freak/32BlitDoom

**Comment by Daft-Freak** [comment]
Hmm, just thought that there's no `delete_file`...
