### ISSUE TITLE
Graphic assets (missing) for examples

### ISSUE THREAD

**Issue by HeadBoffin** [pimoroni/32blit-beta#88]
It would be very useful in reading the examples code if the original graphic assets (png/psd/gif/jpeg) could be put in the repository, please. Will certainly help with #17

**Comment by Gadgetoid** [comment]
Agreed! Will look into doing this- I think a number of the assets I've used have got lost in weird directories or backups (due to some computer trouble) so it might take some sleuthing to find them.

**Comment by Gadgetoid** [comment]
Started to fix this in: https://github.com/pimoroni/32blit-beta/commit/42758cea63bbb4e854e4622984808ebe81de6f64
